# Generated by Django 4.1.7 on 2023-03-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='landlords', to='api.landlord'),
            preserve_default=False,
        ),
    ]
