# Generated by Django 5.0.6 on 2024-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_management_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretakers',
            old_name='subject_name',
            new_name='caretaker_name',
        ),
        migrations.RenameField(
            model_name='tenantresult',
            old_name='subject_id',
            new_name='caretaker_id',
        ),
    ]
